---

- group: name={{ parity_group }} system=yes state=present
- user: name={{ parity_user }} group={{ parity_group }} home={{ parity_home }} shell=/bin/false state=present

#- name: download parity bin file
#  get_url: url={{ parity_source }} dest={{ parity_dst_bindir }}/parity checksum={{ parity_sum }}

#- name: copy parity bin file
#  copy: src=files/parity dest={{ parity_dst_bindir }}/parity owner=root group=staff mode=0755

- name: "check installed parity version"
  shell: parity --version | grep -o -e 'Parity/v.*$'
  register: parity_version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  always_run: true

- set_fact: parity_installed={{ parity_version.stdout_lines[0] is defined and parity_version.stdout_lines[0] == parity_version_string }}

- name: "install parity .deb package"
  apt: deb={{ parity_deb_url }}
  when: not parity_installed

- name: "systemd parity service configuration file"
  template: src=templates/parity.service.j2 dest=/etc/systemd/system/parity.service owner=root group=root mode=0644
  notify:
    - reload systemd

- meta: flush_handlers

- name: "service parity enabled"
  service: name=parity enabled=yes state=started
